# Generated by Django 4.0.4 on 2022-04-12 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('children', models.CharField(max_length=100)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discugraph_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('children', models.CharField(max_length=100)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discugraph_app.user')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discugraph_app.topic')),
            ],
        ),
    ]
